### ISSUE TITLE
Project Peer Review

### ISSUE THREAD

**Issue by SebasRSoler** [ehsueh2/project#4]
i. Technical issues/bugs

1. Review links for Yangmingshan National Park and Shilin Night Market do not work, are not linked to any other page. 
2. The Structure and format of the sitemap can be improved visually, including margins for all pages. 

ii. Suggestions on Content

1. The destination pages can include pictures and a longer description. 
2. All content would be more visually appealing if centered and with margins that will prevent the words from spanning the whole width of the page. 

Overall, great work!

**Comment by ehsueh2** [comment]
Fixed it. Thank you for the feedback!
